app = "letswrite-frontend"

primary_region = "bom"

[build]
  dockerfile = "frontend/Dockerfile"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
